# BASEPROMPT= ("The following is a description of a certain feature of text and a list of examples that contain the feature.\n"
#              "Description: \n"
#              "References to the Antichrist, the Apocalypse and conspiracy theories related to those topics. \n"
#              "Sentences:\n"
#              " by which he distinguishes Antichrist is, that he would rob God of his honour and take it to himself, he gives the leading feature which we ought \n"
#              " would be destroyed. The worlds economy would likely collapse as a result and could usher in a one world government movement. I wrote a small 6 page \n" 
#              "3 begins. And the rise of Antichrist. Get ready with God that you would be found worthy to escape the horrors that will fall on earth. \n" 
#              "Description: \n"
#              "Sentences containing digits forming a four-digit year, \n"
#              "Sentences:\n"
#              " 20, 2013 at 7:41 pm Martin Smith\nThis is all very interesting to me. I am related \n"
#              " of 2012. In other words, Italy's economy is now contracting at an at least 0.3% annualized run \n"
#              "end 2012 levels). In the first quarter of 2013, we expect revenue to be up slightly from the fourth quarter \n"
#              "Description: \n"
#              "Text related to banking and financial institutions \n"
#              "Sentences:\n"
#              ": He is on the Board of Directors with the Lumbee Bank jA course, at the present\ntime, he has a leave of absence with \n"
#              " refurbishing the Bank’s branches.\nBIP reached 400 thousand users in one year\nThe use of BIP has already doubled\nThe \n"
#              " the Federal Deposit Insurance Corp.\nMr. Ranzini would not say where University plans to open loan offices in the future.Beyond Michigan and the \n"
#              )
BASEPROMPT= ("The following is a description of a certain feature of text and a list of examples that contain the feature.\n"
             "Description: \n"
             "References to the Antichrist, the Apocalypse and conspiracy theories related to those topics. \n"
             "Sentences:\n"
             " distinguishes Antichrist is, that he would rob \n"
             " worlds economy would likely collapse as a result  \n" 
             "3 begins. And the rise of Antichrist. Get ready with  \n" 
             "Description: \n"
             "Sentences containing digits forming a four-digit year, \n"
             "Sentences:\n"
             " 20, 2013 at 7:41 pm Martin Smith \n"
             " of 2012. In other words, Italy's  \n"
             "end 2012 levels). In the first quarter  \n"
             "Description: \n"
             "Text related to banking and financial institutions \n"
             "Sentences:\n"
             ": He is on the Board of Directors with the Lumbee Bank  \n"
             " refurbishing the Bank’s branches. \n"
             " the Federal Deposit Insurance Corp. \n"
             )