BASEPROMPT= ("The following is a description of a certain feature of text and a list of examples that contain the feature.\n"
             "Description: \n"
             "'Sentences about swimming' \n"
             "'I love swimming, specially in the summer.'\n"
             "'I like to swim in the pool, I usually go every week.'\n" 
             "'When I go on vacation, I usually go to the beach, because I love swimming.'\n" 
             "'When I watch the Olympics, I prefer swimming competitions.'\n"
             "Description: \n"
             "'Sentences using female pronouns' \n"
             "'Mary went to the store. She bought a dress.' \n"
             "'When going over the crossing, she saw a woman with a baby.' \n"
             "'Doctor Vanessa is a good doctor. She comes to the hospital every week.' \n"
             "Description: \n"
             "'The word 'dog'' \n"
             "'There are cats and dogs in the house.' \n"
             "'My dog's name is Max.' \n"
             )